#ifndef __RTZassistPanelMain__
#define __RTZassistPanelMain__

/**
@file
Subclass of PanelMain, which is generated by wxFormBuilder.
*/

#ifdef WX_PRECOMP
#include "wx/wx.h"
#endif


#include "RTZassistUI.h"
#include "test.h"

//// end generated include
#include "wx/dir.h"
#include <wx/msgdlg.h>
#include <string.h>
#include <list>
#include <vector>
#include <wx/arrstr.h>
#include <wx/textfile.h>
#include <wx/stdpaths.h>
#include <iostream>
#include <fstream>
#include <list>
#include <wx/tokenzr.h>

#include "tinyxml2.h"


class waypoint;
class route;

class waypoint
{
public:
	wxString id;
	wxString name;
	wxString lat, lon;
};

class route
{
public:
	
	wxString routeName;
	std::vector<waypoint> waypoints;
	wxArrayString m_arrayPoints;
};


using namespace std;


/** Implementing PanelMain */
class RTZassistPanelMain : public PanelMain
{
	protected:
		// Handlers for PanelMain events.
		void OnReadGPX(wxCommandEvent& event);
		bool ReadGPX();

		void OnReadRTZ(wxCommandEvent& event);
		void ReadRTZ(string schema, string rtz);

		void OnValidateRTZ( wxCommandEvent& event );
		void ValidateRTZ(string schema, string rtz);

		void OnExportRTZ(wxCommandEvent& event);
		int  ExportRTZ();

		void OnExportGPX(wxCommandEvent& event);
		int  ExportGPX();

		void OnClearTextbox(wxCommandEvent& event);
		void ClearTextbox();

		route GPXtoWaypoints(wxString myGPX);	
		
	public:
		/** Constructor */
		RTZassistPanelMain( wxWindow* parent );
		string testString;
		string startURI;
		wxString gpxFileName;
		wxString filename;
		wxArrayString waypointsList;

		tinyxml2::XMLNode* waypoints;

		route myRoute;
		vector<waypoint> m_waypointList;
		waypoint myPoint;
		vector<waypoint> my_positions;

		tinyxml2::XMLDocument xmlDoc;
		
		
	private:
	//// end generated class members
        

};

#endif // __RTZassistPanelMain__
