#ifndef __RTZassistFrameMain__
#define __RTZassistFrameMain__

/**
@file
Subclass of FrameMain, which is generated by wxFormBuilder.
*/

#include "RTZassistUI.h"


//// end generated include

/** Implementing FrameMain */
class RTZassistFrameMain : public FrameMain
{
	public:
		/** Constructor */
		RTZassistFrameMain( wxWindow* parent );
	//// end generated class members

};

#endif // __RTZassistFrameMain__
